### ISSUE TITLE
Gradle bug

### ISSUE THREAD

**Issue by BenCherif** [playmoweb/store2realm#5]
i can't add the library using gradle  i get this error .
Error:(134, 13) Failed to resolve: com.github.playmoweb:store2realm:3.0.0

i've added maven { url 'https://jitpack.io' } to root gradle but not working .

**Comment by tspoke** [comment]
Hi @BenCherif , please use this version : `com.github.playmoweb:store2realm:3.0.1`

**Comment by BenCherif** [comment]
Ok thanks thats work for me .
